# Generated by Django 2.2.1 on 2020-05-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthUser',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(blank=True, max_length=50, null=True)),
                ('nikename', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
            ],
            options={
                'verbose_name': 'oauth用户',
                'verbose_name_plural': 'oauth用户',
                'db_table': 'bg_user',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('ar_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ar_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='Myauth.OAuthUser')),
            ],
            options={
                'verbose_name': '书列表',
                'verbose_name_plural': '书列表',
                'db_table': 'bg_books',
            },
        ),
    ]
