# Generated by Django 2.2.1 on 2020-05-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthuser',
            name='counts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
