# Generated by Django 3.0.5 on 2020-06-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='创建来源'),
        ),
    ]
